[package]
name = "trading-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apca = "0.26.2"
log = "0.4.17"
url = "2.3.1"
clap = { version = "3.0", features = ["derive"] }
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "signal"] }
exitcode = "1.1.2"
serde = { version = "1.0", features = ["derive"] }
libc = "0.2.142"
num-decimal = {version = "0.2.4", default-features = false, features = ["num-v04", "serde"]}
futures = {version = "0.3", default-features = false}
serde_json = "1.0.96"
